export const actionData = [
  {
    id: 1,
    english: "buy",
    tagalog: "bumili",
    kapampangan: "sali",
    icon: require("../assets/Actions/BUY.png"),
  },
  {
    id: 2,
    english: "fly",
    tagalog: "lipad",
    kapampangan: "sulagpo",
    icon: require("../assets/Actions/FLY.jpg"),
  },
  {
    id: 3,
    english: "get",
    tagalog: "makuha",
    kapampangan: "kumwa",
    icon: require("../assets/Actions/GET.jpg"),
  },
  {
    id: 4,
    english: "give",
    tagalog: "bigyan",
    kapampangan: "denan",
    icon: require("../assets/Actions/GIVE.jpg"),
  },
  {
    id: 5,
    english: "Go",
    tagalog: "Punta",
    kapampangan: "Munta",
    icon: require("../assets/Actions/GO.jpg"),
  },
  {
    id: 6,
    english: "gulp",
    tagalog: "lagok",
    kapampangan: "aldukan",
    icon: require("../assets/Actions/GULP.jpg"),
  },
  {
    id: 7,
    english: "jump",
    tagalog: "talon",
    kapampangan: "lukdang",
    icon: require("../assets/Actions/JUMP.jpg"),
  },
  {
    id: 8,
    english: "leave",
    tagalog: "iwan",
    kapampangan: "lakwan",
    icon: require("../assets/Actions/LEAVE.png"),
  },
  {
    id: 9,
    english: "participate",
    tagalog: "makilahok",
    kapampangan: "makipagtalamitam",
    icon: require("../assets/Actions/PARTICIPATE.jpg"),
  },
  {
    id: 10,
    english: "pilfer",
    tagalog: "kumupit",
    kapampangan: "mangoryet",
    icon: require("../assets/Actions/PILFER.jpg"),
  },
  {
    id: 11,
    english: "run",
    tagalog: "takbo",
    kapampangan: "pulayi",
    icon: require("../assets/Actions/RUN.jpeg"),
  },
  {
    id: 12,
    english: "slice",
    tagalog: "hiwa",
    kapampangan: "gili",
    icon: require("../assets/Actions/SLICE.png"),
  },
  {
    id: 13,
    english: "slurp",
    tagalog: "higupin",
    kapampangan: "ilupan",
    icon: require("../assets/Actions/SLURP.jpg"),
  },
  {
    id: 14,
    english: "steal",
    tagalog: "magnakaw",
    kapampangan: "magnako",
    icon: require("../assets/Actions/STEAL.jpg"),
  },
  {
    id: 15,
    english: "step on",
    tagalog: "tumuntong",
    kapampangan: "dakurak",
    icon: require("../assets/Actions/STEP.jpg"),
  },
  {
    id: 16,
    english: "stop",
    tagalog: "huminto",
    kapampangan: "tuknang",
    icon: require("../assets/Actions/STOP.jpg"),
  },
  {
    id: 17,
    english: "to apologize",
    tagalog: "humingi ng tawad",
    kapampangan: "mangamanung kapagmakitan",
    icon: require("../assets/Actions/APOLOGIZE.jpg"),
  },
  {
    id: 18,
    english: "to call",
    tagalog: "tawagan",
    kapampangan: "awsan",
    icon: require("../assets/Actions/CALL.jpg"),
  },
  {
    id: 19,
    english: "to catch fish",
    tagalog: "mamingwit",
    kapampangan: "mamadwas",
    icon: require("../assets/Actions/CATCH.jpg"),
  },
  {
    id: 20,
    english: "to cut",
    tagalog: "gupitin",
    kapampangan: "pututan",
    icon: require("../assets/Actions/CUT.jpg"),
  },
  {
    id: 21,
    english: "to fix",
    tagalog: "ayusin",
    kapampangan: "samasan",
    icon: require("../assets/Actions/FIX.jpeg"),
  },
  {
    id: 22,
    english: "to play",
    tagalog: "maglaro",
    kapampangan: "pyalungan",
    icon: require("../assets/Actions/PLAY.png"),
  },
  {
    id: 23,
    english: "to shout",
    tagalog: "sumigaw",
    kapampangan: "gulisak",
    icon: require("../assets/Actions/SHOUT.png"),
  },
  {
    id: 24,
    english: "to speak",
    tagalog: "magsalita",
    kapampangan: "sumabi",
    icon: require("../assets/Actions/SPEAK.jpg"),
  },
  {
    id: 25,
    english: "to wash clothes",
    tagalog: "maglaba",
    kapampangan: "mamipi",
    icon: require("../assets/Actions/WASH.jpg"),
  },
  {
    id: 26,
    english: "wear clothes",
    tagalog: "mag bihis",
    kapampangan: "maniblas",
    icon: require("../assets/Actions/WEAR.jpg"),
  },
]
