export const actionData = [
  {
    id: 1,
    english: "buy",
    tagalog: "bumili",
    kapampangan: "sali",
    luther: "sáli",
    bergano: "",
    icon: require("../assets/Actions/BUY.png"),
  },
  {
    id: 2,
    english: "fly",
    tagalog: "lipad",
    kapampangan: "sulagpo",
    luther: "sulápo",
    bergano: "lipao",
    icon: require("../assets/Actions/FLY.jpg"),
  },
  {
    id: 3,
    english: "get",
    tagalog: "makuha",
    kapampangan: "kumwa",
    luther: "apaquicuánan",
    bergano: "Acua / cacua / Quiningua / cuma",
    icon: require("../assets/Actions/GET.jpg"),
  },
  {
    id: 4,
    english: "give",
    tagalog: "bigyan",
    kapampangan: "denan",
    luther: "munié",
    bergano: "",
    icon: require("../assets/Actions/GIVE.jpg"),
  },
  {
    id: 5,
    english: "Go",
    tagalog: "Punta",
    kapampangan: "Munta",
    luther: "umié",
    bergano: "",

    icon: require("../assets/Actions/GO.jpg"),
  },
  {
    id: 7,
    english: "jump",
    tagalog: "talon",
    kapampangan: "lukdang",
    luther: "lucsú",
    bergano: "balsic / lucsu / lundagilin /lacuan  ",
    icon: require("../assets/Actions/JUMP.jpg"),
  },
  {
    id: 8,
    english: "leave",
    tagalog: "iwan",
    kapampangan: "lakwan",
    luther: "paintúlut",
    bergano: "bilin / lacuan ",
    icon: require("../assets/Actions/LEAVE.png"),
  },
  {
    id: 9,
    english: "participate",
    tagalog: "makilahok",
    kapampangan: "makipagtalamitam",
    luther: "Mákipagtalamítam",
    bergano: "dumame / irame / demayan / miraramay",
    icon: require("../assets/Actions/PARTICIPATE.jpg"),
  },
  {
    id: 10,
    english: "pilfer",
    tagalog: "kumupit",
    kapampangan: "mangoryet",
    luther: "",
    bergano: "",
    icon: require("../assets/Actions/PILFER.jpg"),
  },
  {
    id: 11,
    english: "run",
    tagalog: "takbo",
    kapampangan: "pulayi",
    luther: "mulaí",
    bergano: "pulayi / mulayi / mamulayi",
    icon: require("../assets/Actions/RUN.jpeg"),
  },
  {
    id: 12,
    english: "slice",
    tagalog: "hiwa",
    kapampangan: "gili",
    luther: "guilí",
    bergano: "guili /mangguili / mangili",
    icon: require("../assets/Actions/SLICE.png"),
  },
  {
    id: 14,
    english: "steal",
    tagalog: "magnakaw",
    kapampangan: "magnako",
    luther: "manáco",
    bergano: "manaco",
    icon: require("../assets/Actions/STEAL.jpg"),
  },
  {
    id: 15,
    english: "step on",
    tagalog: "tumuntong",
    kapampangan: "dakurak",
    luther: "",
    bergano: "dalpak / manyalpac / dilpac",
    icon: require("../assets/Actions/STEP.jpg"),
  },
  {
    id: 16,
    english: "stop",
    tagalog: "huminto",
    kapampangan: "tuknang",
    luther: "tucnáng",
    bergano: "tucnang / ",
    icon: require("../assets/Actions/STOP.jpg"),
  },
  {
    id: 17,
    english: "apologize",
    tagalog: "humingi ng tawad",
    kapampangan: "mangamanung kapagmakitan",
    luther: "Mangamánung capgmasakítan",
    bergano: "Sisi / Sisisi / Pamanisi",
    icon: require("../assets/Actions/APOLOGIZE.jpg"),
  },
  {
    id: 18,
    english: "call",
    tagalog: "tawagan",
    kapampangan: "awsan",
    luther: "máus, culáit",
    bergano: "Yaus / Maus / Ivaus / Mañiaus, ",
    icon: require("../assets/Actions/CALL.jpg"),
  },
  {
    id: 19,
    english: "catch fish",
    tagalog: "mamingwit",
    kapampangan: "mamadwas",
    luther: "",
    bergano: "",
    icon: require("../assets/Actions/CATCH.jpg"),
  },
  {
    id: 20,
    english: "cut",
    tagalog: "gupitin",
    kapampangan: "pututan",
    luther: "cutúran",
    bergano: "Bangal / Bangalan / cauani / cutud /",
    icon: require("../assets/Actions/CUT.jpg"),
  },
  {
    id: 21,
    english: "fix",
    tagalog: "ayusin",
    kapampangan: "samasan",
    luther: "",
    bergano: "Amasamas / Miamasamas",
    icon: require("../assets/Actions/FIX.jpeg"),
  },
  {
    id: 22,
    english: "play",
    tagalog: "maglaro",
    kapampangan: "pyalungan",
    luther: "pyálung",
    bergano: "",
    icon: require("../assets/Actions/PLAY.png"),
  },
  {
    id: 23,
    english: "shout",
    tagalog: "sumigaw",
    kapampangan: "gulisak",
    luther: "",
    bergano: "bulyao / Cul-lyao / ",
    icon: require("../assets/Actions/SHOUT.png"),
  },
  {
    id: 24,
    english: "speak",
    tagalog: "magsalita",
    kapampangan: "sumabi",
    luther: "mañábi",
    bergano: "",
    icon: require("../assets/Actions/SPEAK.jpg"),
  },
  {
    id: 25,
    english: "wash clothes",
    tagalog: "maglaba",
    kapampangan: "mamipi",
    luther: "Mamipi",
    bergano: "Pipi / Mamipi ",
    icon: require("../assets/Actions/WASH.jpg"),
  },
  {
    id: 26,
    english: "own",
    tagalog: "sarili",
    kapampangan: "bandi",
    luther: "bandi",
    bergano: "bandi",
    icon: require("../assets/Actions/WEAR.jpg"),
  },
]
