export const actionData = [
  {
    id: 1,
    english: "buy",
    tagalog: "bumili",
    kapampangan: "sali",
    luther: "sáli",
    bergano: "",
    icon: require("../assets/Actions/BUY.png"),
    voice_kapampangan: require("../assets/Voice/Action/Buy.m4a"),
  },
  {
    id: 2,
    english: "fly",
    tagalog: "lipad",
    kapampangan: "sulagpo",
    luther: "sulápo",
    bergano: "lipao",
    icon: require("../assets/Actions/TOFLY.png"),
    voice_kapampangan: require("../assets/Voice/Action/Fly.m4a"),
  },
  {
    id: 3,
    english: "get",
    tagalog: "makuha",
    kapampangan: "kumwa",
    luther: "apaquicuánan",
    bergano: "Acua / cacua / Quiningua / cuma",
    icon: require("../assets/Actions/GET.png"),
    voice_kapampangan: require("../assets/Voice/Action/Get.m4a"),
  },
  {
    id: 4,
    english: "give",
    tagalog: "bigyan",
    kapampangan: "denan",
    luther: "munié",
    bergano: "",
    icon: require("../assets/Actions/TOGIVE.png"),
    voice_kapampangan: require("../assets/Voice/Action/Give.m4a"),
  },
  {
    id: 5,
    english: "Go",
    tagalog: "Punta",
    kapampangan: "Munta",
    luther: "umié",
    bergano: "",
    icon: require("../assets/Actions/GO.png"),
    voice_kapampangan: require("../assets/Voice/Action/Go.m4a"),
  },
  {
    id: 7,
    english: "jump",
    tagalog: "talon",
    kapampangan: "lukdang",
    luther: "lucsú",
    bergano: "balsic / lucsu / lundagilin /lacuan  ",
    icon: require("../assets/Actions/JUMP.png"),
    voice_kapampangan: require("../assets/Voice/Action/Jump.m4a"),
  },
  {
    id: 8,
    english: "leave",
    tagalog: "iwan",
    kapampangan: "lakwan",
    luther: "paintúlut",
    bergano: "bilin / lacuan ",
    icon: require("../assets/Actions/LEAVE.png"),
    voice_kapampangan: require("../assets/Voice/Action/Leave.m4a"),
  },
  {
    id: 9,
    english: "participate",
    tagalog: "makilahok",
    kapampangan: "makipagtalamitam",
    luther: "Mákipagtalamítam",
    bergano: "dumame / irame / demayan / miraramay",
    icon: require("../assets/Actions/PARTICIPATE.png"),
    voice_kapampangan: require("../assets/Voice/Action/Participate.m4a"),
  },
  {
    id: 10,
    english: "pilfer",
    tagalog: "kumupit",
    kapampangan: "mangoryet",
    luther: "",
    bergano: "",
    icon: require("../assets/Actions/PILTERORFLICHING.png"),
    voice_kapampangan: require("../assets/Voice/Action/Pilfer.m4a"),
  },
  {
    id: 11,
    english: "run",
    tagalog: "takbo",
    kapampangan: "pulayi",
    luther: "mulaí",
    bergano: "pulayi / mulayi / mamulayi",
    icon: require("../assets/Actions/RUN.png"),
    voice_kapampangan: require("../assets/Voice/Action/Run.m4a"),
  },
  {
    id: 12,
    english: "slice",
    tagalog: "hiwa",
    kapampangan: "gili",
    luther: "guilí",
    bergano: "guili /mangguili / mangili",
    icon: require("../assets/Actions/SLICE.png"),
    voice_kapampangan: require("../assets/Voice/Action/Slice.m4a"),
  },
  {
    id: 14,
    english: "steal",
    tagalog: "magnakaw",
    kapampangan: "magnako",
    luther: "manáco",
    bergano: "manaco",
    icon: require("../assets/Actions/STEAL.png"),
    voice_kapampangan: require("../assets/Voice/Action/Steal.m4a"),
  },
  {
    id: 15,
    english: "step on",
    tagalog: "tumuntong",
    kapampangan: "dakurak",
    luther: "",
    bergano: "dalpak / manyalpac / dilpac",
    icon: require("../assets/Actions/STEP_ON.png"),
    voice_kapampangan: require("../assets/Voice/Action/Step_on.m4a"),
  },
  {
    id: 16,
    english: "stop",
    tagalog: "huminto",
    kapampangan: "tuknang",
    luther: "tucnáng",
    bergano: "tucnang / ",
    icon: require("../assets/Actions/STOP.png"),
    voice_kapampangan: require("../assets/Voice/Action/Stop.m4a"),
  },
  {
    id: 17,
    english: "apologize",
    tagalog: "humingi ng tawad",
    kapampangan: "mangamanung kapagmakitan",
    luther: "Mangamánung capgmasakítan",
    bergano: "Sisi / Sisisi / Pamanisi",
    icon: require("../assets/Actions/TOAPOLOGIZE.png"),
    voice_kapampangan: require("../assets/Voice/Action/Apologize.m4a"),
  },
  {
    id: 18,
    english: "call",
    tagalog: "tawagan",
    kapampangan: "awsan",
    luther: "máus, culáit",
    bergano: "Yaus / Maus / Ivaus / Mañiaus, ",
    icon: require("../assets/Actions/TOCALL.png"),
    voice_kapampangan: require("../assets/Voice/Action/Call.m4a"),
  },
  {
    id: 19,
    english: "catch fish",
    tagalog: "mamingwit",
    kapampangan: "mamadwas",
    luther: "",
    bergano: "",
    icon: require("../assets/Actions/CATCH.jpg"),
    voice_kapampangan: require("../assets/Voice/Action/Fish_catching.m4a"),
  },
  {
    id: 20,
    english: "cut",
    tagalog: "gupitin",
    kapampangan: "pututan",
    luther: "cutúran",
    bergano: "Bangal / Bangalan / cauani / cutud /",
    icon: require("../assets/Actions/TOCUT.png"),
    voice_kapampangan: require("../assets/Voice/Action/Cut.m4a"),
  },
  {
    id: 21,
    english: "fix",
    tagalog: "ayusin",
    kapampangan: "samasan",
    luther: "",
    bergano: "Amasamas / Miamasamas",
    icon: require("../assets/Actions/TOFIX.png"),
    voice_kapampangan: require("../assets/Voice/Action/Fix.m4a"),
  },
  // {
  //   id: 22,
  //   english: "play",
  //   tagalog: "maglaro",
  //   kapampangan: "pyalungan",
  //   luther: "pyálung",
  //   bergano: "",
  //   icon: require("../assets/Actions/PLAY.png"),
  //   voice_kapampangan: require("../assets/Voice/Action/Play.m4a"),
  // },
  {
    id: 23,
    english: "shout",
    tagalog: "sumigaw",
    kapampangan: "gulisak",
    luther: "",
    bergano: "bulyao / Cul-lyao / ",
    icon: require("../assets/Actions/TOSHOUT.png"),
    voice_kapampangan: require("../assets/Voice/Action/Shout.m4a"),
  },
  {
    id: 24,
    english: "speak",
    tagalog: "magsalita",
    kapampangan: "sumabi",
    luther: "mañábi",
    bergano: "",
    icon: require("../assets/Actions/SPEAK.png"),
    voice_kapampangan: require("../assets/Voice/Action/Speak.m4a"),
  },
  {
    id: 25,
    english: "wash clothes",
    tagalog: "maglaba",
    kapampangan: "mamipi",
    luther: "Mamipi",
    bergano: "Pipi / Mamipi ",
    icon: require("../assets/Actions/TOWASHCLOTHES.png"),
    voice_kapampangan: require("../assets/Voice/Action/Washing_clothes.m4a"),
  },
  {
    id: 26,
    english: "own",
    tagalog: "sarili",
    kapampangan: "bandi",
    luther: "bandi",
    bergano: "bandi",
    icon: require("../assets/Actions/OWN.png"),
    voice_kapampangan: require("../assets/Voice/Action/Own.m4a"),
  },
]
