export const bodyParts = [
  {
    id: 1,
    english: "Ears",
    tagalog: "Tenga",
    kapampangan: "Balugbug",
    luther: "balugbúg",
    bergano: "balugbug",
    icon: require("../assets/bodyParts/EAR.png"),
    voice_kapampangan: require("../assets/Voice/Body/Ears.m4a"),
  },
  {
    id: 2,
    english: "Elbow",
    tagalog: "Siko",
    kapampangan: "Siku",
    icon: require("../assets/bodyParts/ELBOW_SIKU.png"),
    voice_kapampangan: require("../assets/Voice/Body/Elbow.m4a"),
  },
  {
    id: 3,
    english: "Eyes",
    tagalog: "Mata",
    kapampangan: "Mata",
    luther: "matá",
    bergano: "mata",
    icon: require("../assets/bodyParts/EYES.png"),
    voice_kapampangan: require("../assets/Voice/Body/Eyes.m4a"),
  },
  {
    id: 4,
    english: "Head",
    tagalog: "ulo",
    kapampangan: "buntuc",
    luther: "buntúc",
    bergano: "buntoc",
    icon: require("../assets/bodyParts/HEAD.png"),
    voice_kapampangan: require("../assets/Voice/Body/Head.m4a"),
  },
  {
    id: 5,
    english: "Leg",
    tagalog: "binti",
    kapampangan: "puad",
    luther: "puád",
    bergano: "puád",
    icon: require("../assets/bodyParts/LEG.png"),
    voice_kapampangan: require("../assets/Voice/Body/Leg.m4a"),
  },
  {
    id: 6,
    english: "Fingers",
    tagalog: "Daliri",
    kapampangan: "Taliri",
    luther: "talíri",
    bergano: "taliri",
    icon: require("../assets/bodyParts/FINGER.png"),
    voice_kapampangan: require("../assets/Voice/Body/Fingers.m4a"),
  },
  {
    id: 7,
    english: "Abdomen",
    tagalog: "Tiyan",
    kapampangan: "atian",
    luther: "atián",
    bergano: "atian",
    icon: require("../assets/bodyParts/ABDOMEN.png"),
    voice_kapampangan: require("../assets/Voice/Body/Stomach.m4a"),
  },
  {
    id: 8,
    english: "Hands",
    tagalog: "Kamay",
    kapampangan: "Gamat",
    luther: "gámat",
    bergano: "gamat",
    icon: require("../assets/bodyParts/HANDS.png"),
    voice_kapampangan: require("../assets/Voice/Body/Hands.m4a"),
  },
  {
    id: 9,
    english: "Foot",
    tagalog: "Paa",
    kapampangan: "Bitis",
    luther: "bitís",
    bergano: "bitis",
    icon: require("../assets/bodyParts/FOOT.png"),
    voice_kapampangan: require("../assets/Voice/Body/Feet.m4a"),
  },

  {
    id: 11,
    english: "Body",
    tagalog: "katawan",
    kapampangan: "catauan",
    luther: "catáuan",
    bergano: "catauan",
    icon: require("../assets/bodyParts/BODY.png"),
    voice_kapampangan: require("../assets/Voice/Body/Body.m4a"),
  },
  {
    id: 12,
    english: "Mouth",
    tagalog: "Bibig",
    kapampangan: "Asbuk",
    luther: "puád",
    bergano: "puad",
    icon: require("../assets/bodyParts/MOUTH.png"),
    voice_kapampangan: require("../assets/Voice/Body/Mouth.m4a"),
  },
  {
    id: 13,
    english: "Ankle",
    tagalog: "bukung-bukong",
    kapampangan: "bucung bitis",
    luther: "bucúng bitis",
    bergano: "bucung bitis",
    icon: require("../assets/bodyParts/ANKLE.png"),
    voice_kapampangan: require("../assets/Voice/Body/Ankle.m4a"),
  },
  {
    id: 14,
    english: "Neck",
    tagalog: "Leeg",
    kapampangan: "Batal",
    luther: "bátal",
    bergano: "batal",
    icon: require("../assets/bodyParts/NECK.png"),
    voice_kapampangan: require("../assets/Voice/Body/Neck.m4a"),
  },
  {
    id: 15,
    english: "Nose",
    tagalog: "Ilong",
    kapampangan: "Arung",
    luther: "árung",
    bergano: "áron",
    icon: require("../assets/bodyParts/NOSE.png"),
    voice_kapampangan: require("../assets/Voice/Body/Nose.m4a"),
  },
  {
    id: 16,
    english: "Shoulder",
    tagalog: "Balikat",
    kapampangan: "Pago",
    luther: "pagó",
    bergano: "pagao",
    icon: require("../assets/bodyParts/SHOULDER.png"),
    voice_kapampangan: require("../assets/Voice/Body/Shoulder.m4a"),
  },
  {
    id: 17,
    english: "Cheek",
    tagalog: "pisngi",
    kapampangan: "pisngi",
    luther: "pisnǵi",
    bergano: "pisngi",
    icon: require("../assets/bodyParts/CHEEK.png"),
    voice_kapampangan: require("../assets/Voice/Body/Cheek.m4a"),
  },
  {
    id: 18,
    english: "Chin",
    tagalog: "baba",
    kapampangan: "baba",
    luther: "babá",
    bergano: "babâ",
    icon: require("../assets/bodyParts/CHIN.png"),
    voice_kapampangan: require("../assets/Voice/Body/Chin.m4a"),
  },
  {
    id: 19,
    english: "Sole",
    tagalog: "talampakan",
    kapampangan: "talampacan",
    luther: "talampácan",
    bergano: "talampacan",
    icon: require("../assets/bodyParts/SOLE.png"),
    voice_kapampangan: require("../assets/Voice/Body/Sole.m4a"),
  },
  {
    id: 20,
    english: "Knee",
    tagalog: "tuhod",
    kapampangan: "tud",
    luther: "túd",
    bergano: "tud",
    icon: require("../assets/bodyParts/KNEE.png"),
    voice_kapampangan: require("../assets/Voice/Body/Knee.m4a"),
  },
  {
    id: 21,
    english: "Waist",
    tagalog: "baywang",
    kapampangan: "auacan",
    luther: "auácan",
    bergano: "auacan",
    icon: require("../assets/bodyParts/WAIST.png"),
    voice_kapampangan: require("../assets/Voice/Body/Waist.m4a"),
  },
  {
    id: 22,
    english: "Hair",
    tagalog: "buhok",
    kapampangan: "buac",
    luther: "buác",
    bergano: "buac",
    icon: require("../assets/bodyParts/HAIR.png"),
    voice_kapampangan: require("../assets/Voice/Body/Hair.m4a"),
  },
]
