export const bodyParts = [
  {
    id: 1,
    english: "Ears",
    tagalog: "Tenga",
    kapampangan: "Balugbug",
    luther: "balugbúg",
    bergano: "balugbug",
    icon: require("../assets/bodyParts/EARS_BALUGBUG.png"),
  },
  {
    id: 2,
    english: "Elbow",
    tagalog: "Siko",
    kapampangan: "Siku",
    icon: require("../assets/bodyParts/ELBOW_SIKU.png"),
  },
  {
    id: 3,
    english: "Eyes",
    tagalog: "Mata",
    kapampangan: "Mata",
    luther: "matá",
    bergano: "mata",
    icon: require("../assets/bodyParts/EYES_MATA.jpg"),
  },
  {
    id: 4,
    english: "Head",
    tagalog: "ulo",
    kapampangan: "buntuc",
    luther: "buntúc",
    bergano: "buntoc",
    icon: require("../assets/bodyParts/FACE_LUPA.png"),
  },
  {
    id: 5,
    english: "Leg",
    tagalog: "binti",
    kapampangan: "puad",
    luther: "puád",
    bergano: "puád",
    icon: require("../assets/bodyParts/LEGS_BUTIT.png"),
  },
  {
    id: 6,
    english: "Fingers",
    tagalog: "Daliri",
    kapampangan: "Taliri",
    luther: "talíri",
    bergano: "taliri",
    icon: require("../assets/bodyParts/FINGERS_TALIRI.jpg"),
  },
  {
    id: 7,
    english: "Abdomen",
    tagalog: "Tiyan",
    kapampangan: "atian",
    luther: "atián",
    bergano: "atian",
    icon: require("../assets/bodyParts/FOREHEAD_KANUAN.jpg"),
  },
  {
    id: 8,
    english: "Hands",
    tagalog: "Kamay",
    kapampangan: "Gamat",
    luther: "gámat",
    bergano: "gamat",
    icon: require("../assets/bodyParts/HANDS_GAMAT.png"),
  },
  {
    id: 9,
    english: "Foot",
    tagalog: "Paa",
    kapampangan: "Bitis",
    luther: "bitís",
    bergano: "bitis",
    icon: require("../assets/bodyParts/FOOT_TALAMPAKAN.png"),
  },
  {
    id: 10,
    english: "Head",
    tagalog: "Ulo",
    kapampangan: "Buntuk",
    luther: "buntúc",
    bergano: "buntoc",
    icon: require("../assets/bodyParts/HEAD_BUNTUK.jpg"),
  },
  {
    id: 11,
    english: "Body",
    tagalog: "katawan",
    kapampangan: "catauan",
    luther: "catáuan",
    bergano: "catauan",
    icon: require("../assets/bodyParts/LEGS_BUTIT.png"),
  },
  {
    id: 12,
    english: "Mouth",
    tagalog: "Bibig",
    kapampangan: "Asbuk",
    luther: "puád",
    bergano: "puad",
    icon: require("../assets/bodyParts/MOUTH_ASBUK.jpg"),
  },
  {
    id: 13,
    english: "Ankle",
    tagalog: "bukung-bukong",
    kapampangan: "bucung bitis",
    luther: "bucúng bitis",
    bergano: "bucung bitis",
    icon: require("../assets/bodyParts/NAPE_TUNDUN.jpg"),
  },
  {
    id: 14,
    english: "Neck",
    tagalog: "Leeg",
    kapampangan: "Batal",
    luther: "bátal",
    bergano: "batal",
    icon: require("../assets/bodyParts/NECK_BATAL.png"),
  },
  {
    id: 15,
    english: "Nose",
    tagalog: "Ilong",
    kapampangan: "Arung",
    luther: "árung",
    bergano: "áron",
    icon: require("../assets/bodyParts/NOSE_ARUNG.jpg"),
  },
  {
    id: 16,
    english: "Shoulder",
    tagalog: "Balikat",
    kapampangan: "Pago",
    luther: "pagó",
    bergano: "pagao",
    icon: require("../assets/bodyParts/SHOULDER_PAGO.png"),
  },
  {
    id: 17,
    english: "Cheek",
    tagalog: "pisngi",
    kapampangan: "pisngi",
    luther: "pisnǵi",
    bergano: "pisngi",
    icon: require("../assets/bodyParts/TEETH_IPAN.webp"),
  },
  {
    id: 18,
    english: "Chin",
    tagalog: "baba",
    kapampangan: "baba",
    luther: "babá",
    bergano: "babâ",
    icon: require("../assets/bodyParts/TONGUE_DILA.png"),
  },
  {
    id: 19,
    english: "Sole",
    tagalog: "talampakan",
    kapampangan: "talampacan",
    luther: "talampácan",
    bergano: "talampacan",
    icon: require("../assets/bodyParts/TONGUE_DILA.png"),
  },
  {
    id: 20,
    english: "Knee",
    tagalog: "tuhod",
    kapampangan: "tud",
    luther: "túd",
    bergano: "tud",
    icon: require("../assets/bodyParts/TONGUE_DILA.png"),
  },
  {
    id: 21,
    english: "Waist",
    tagalog: "baywang",
    kapampangan: "auacan",
    luther: "auácan",
    bergano: "auacan",
    icon: require("../assets/bodyParts/TONGUE_DILA.png"),
  },
  {
    id: 22,
    english: "Hair",
    tagalog: "buhok",
    kapampangan: "buac",
    luther: "buác",
    bergano: "buac",
    icon: require("../assets/bodyParts/TONGUE_DILA.png"),
  },
]
