export const commonGreetings = [
  {
    id: 1,
    english: "Excuse Me",
    tagalog: "Paumanhin",
    kapampangan: "Panapaya Mu Ku",
    luther: "talampácan",
    bergano: "talampacan",
    icon: require("../assets/commonGreetings/EXCUSEME.jpg"),
  },
  {
    id: 2,
    english: "Good Afternoon",
    tagalog: "Magandang Hapon",
    kapampangan: "Mayap A Gatpanapun",
    luther: "Mayáp a gatpanápun",
    bergano: "",
    icon: require("../assets/commonGreetings/GOODAFTERNOON.jpeg"),
  },
  {
    id: 3,
    english: "Good evening",
    tagalog: "Magandang Gabi",
    kapampangan: "Mayap A Bengi",
    luther: "Mayáp a mabéngi",
    bergano: "",
    icon: require("../assets/commonGreetings/GOODEVENING.jpeg"),
  },
  {
    id: 4,
    english: "Good Morning",
    tagalog: "Magandang Umaga",
    kapampangan: "Mayap A Abak",
    luther: "Mayáp a ábac",
    bergano: "",
    icon: require("../assets/commonGreetings/GOODMORNING.jpeg"),
  },
  {
    id: 5,
    english: "How are you",
    tagalog: "Kamusta",
    kapampangan: "Komusta",
    luther: "talampácan",
    bergano: "talampacan",
    icon: require("../assets/commonGreetings/HOWAREYOU.jpeg"),
  },
  {
    id: 6,
    english: "I love you",
    tagalog: "Mahal kita",
    kapampangan: "Kaluguran Da Ka",
    luther: "talampácan",
    bergano: "talampacan",
    icon: require("../assets/commonGreetings/ILOVEYOU.jpeg"),
  },
  {
    id: 7,
    english: "I Miss You",
    tagalog: "Miss na kita",
    kapampangan: "Agaganaka Da Ka",
    luther: "talampácan",
    bergano: "talampacan",
    icon: require("../assets/commonGreetings/IMISSYOU.jpeg"),
  },
  {
    id: 8,
    english: "Kissing the hand of Elderly",
    tagalog: "Mano po",
    kapampangan: "Siklod pu",
    luther: "talampácan",
    bergano: "talampacan",
    icon: require("../assets/commonGreetings/SIKLOD.jpeg"),
  },
  {
    id: 9,
    english: "Many Thanks",
    tagalog: "Maraming Salamat",
    kapampangan: "Dakal a Salamat",
    luther: "talampácan",
    bergano: "talampacan",
    icon: require("../assets/commonGreetings/THANKS.jpeg"),
  },
  {
    id: 10,
    english: "Welcome",
    tagalog: "Maligayang Pagdating",
    kapampangan: "Malaus Kayu",
    luther: "Mayáp á pañatáng",
    bergano: "",
    icon: require("../assets/commonGreetings/WELCOME.jpeg"),
  },
]
