export const commonGreetings = [
  {
    id: 1,
    english: "Excuse Me",
    tagalog: "Paumanhin",
    kapampangan: "Panapaya Mu Ku",
    luther: "talampácan",
    bergano: "talampacan",
    icon: require("../assets/commonGreetings/Excuseme.png"),
    voice_kapampangan: require("../assets/Voice/Greetings/Excuse_me.m4a"),
  },
  {
    id: 2,
    english: "Good Afternoon",
    tagalog: "Magandang Hapon",
    kapampangan: "Mayap A Gatpanapun",
    luther: "Mayáp a gatpanápun",
    bergano: "",
    icon: require("../assets/commonGreetings/Goodafternoon.png"),
    voice_kapampangan: require("../assets/Voice/Greetings/Good_afternoon.m4a"),
  },
  {
    id: 3,
    english: "Good evening",
    tagalog: "Magandang Gabi",
    kapampangan: "Mayap A Bengi",
    luther: "Mayáp a mabéngi",
    bergano: "",
    icon: require("../assets/commonGreetings/Goodevening.png"),
    voice_kapampangan: require("../assets/Voice/Greetings/Good_evening.m4a"),
  },
  {
    id: 4,
    english: "Good Morning",
    tagalog: "Magandang Umaga",
    kapampangan: "Mayap A Abak",
    luther: "Mayáp a ábac",
    bergano: "",
    icon: require("../assets/commonGreetings/Goodmorning.png"),
    voice_kapampangan: require("../assets/Voice/Greetings/Good_Morning.m4a"),
  },
  {
    id: 5,
    english: "How are you",
    tagalog: "Kamusta",
    kapampangan: "Komusta",
    luther: "talampácan",
    bergano: "talampacan",
    icon: require("../assets/commonGreetings/Howareyou.png"),
    voice_kapampangan: require("../assets/Voice/Greetings/How_are_you.m4a"),
  },
  // {
  //   id: 6,
  //   english: "I love you",
  //   tagalog: "Mahal kita",
  //   kapampangan: "Kaluguran Da Ka",
  //   luther: "talampácan",
  //   bergano: "talampacan",
  //   icon: require("../assets/commonGreetings/Iloveyou.png"),
  // },
  {
    id: 7,
    english: "I Miss You",
    tagalog: "Miss na kita",
    kapampangan: "Agaganaka Da Ka",
    luther: "talampácan",
    bergano: "talampacan",
    icon: require("../assets/commonGreetings/Imissyou.png"),
    voice_kapampangan: require("../assets/Voice/Greetings/I_miss_you.m4a"),
  },
  {
    id: 8,
    english: "Kissing the hand of Elderly",
    tagalog: "Mano po",
    kapampangan: "Siklod pu",
    luther: "talampácan",
    bergano: "talampacan",
    icon: require("../assets/commonGreetings/SIKLOD.jpeg"),
    voice_kapampangan: require("../assets/Voice/Greetings/Bless_me.m4a"),
  },
  {
    id: 9,
    english: "Many Thanks",
    tagalog: "Maraming Salamat",
    kapampangan: "Dakal a Salamat",
    luther: "talampácan",
    bergano: "talampacan",
    icon: require("../assets/commonGreetings/ManyThanks.png"),
    voice_kapampangan: require("../assets/Voice/Greetings/Thank_you.m4a"),
  },
  {
    id: 10,
    english: "Welcome",
    tagalog: "Maligayang Pagdating",
    kapampangan: "Malaus Kayu",
    luther: "Mayáp á pañatáng",
    bergano: "",
    icon: require("../assets/commonGreetings/Welcome.png"),
    voice_kapampangan: require("../assets/Voice/Greetings/Welcome.m4a"),
  },
]
