export const familyData = [
  {
    id: 1,
    english: "Mother",
    tagalog: "nanay",
    kapampangan: "ima",
    luther: "indá",
    bergano: "indá, apo",
  },
  {
    id: 2,
    english: "Father",
    tagalog: "tatay",
    kapampangan: "tatang",
    luther: "ibpá o táta",
    bergano: "apo, ibpá",
  },
  {
    id: 3,
    english: "Parent",
    tagalog: "magulang",
    kapampangan: "pengari",
    luther: "táta o indú",
    bergano: "ári",
  },
  {
    id: 4,
    english: "Older brother ",
    tagalog: "kuya",
    kapampangan: "koya",
    luther: "capatád á laláqu",
    bergano: "caca",
  },
  {
    id: 5,
    english: "Older Sister",
    tagalog: "ate",
    kapampangan: "atchi",
    luther: "capatád á babaí",
    bergano: "caca",
  },
  {
    id: 6,
    english: "Sibling",
    tagalog: "kapatid",
    kapampangan: "capatad",
    luther: "capatád",
    bergano: "",
  },
  {
    id: 7,
    english: "Grandfather",
    tagalog: "lolo",
    kapampangan: "apu",
    luther: "ápung laláquí",
    bergano: "nunu, apo",
  },
  {
    id: 8,
    english: "Grandmother",
    tagalog: "lola",
    kapampangan: "apu",
    luther: "ápung babaí",
    bergn8o: "nunu, apo",
  },
  {
    id: 9,
    english: "Aunt",
    tagalog: "tiya",
    kapampangan: "dara",
    luther: "dára",
    bergano: "dara",
  },
  {
    id: 10,
    english: "Uncle",
    tagalog: "tiyuhin",
    kapampangan: "bapa",
    luther: "bápa",
    bergano: "bapa",
  },
  {
    id: 11,
    english: "Cousin",
    tagalog: "pinsan",
    kapampangan: "pisan",
    luther: "písan",
    bergano: "catuyangan",
  },
  {
    id: 12,
    english: "Younger Sibling",
    tagalog: "nakababatang kapatid",
    kapampangan: "wali",
    luther: "",
    bergano: "wali",
  },
]
