export const familyData = [
  {
    id: 1,
    english: "Mother",
    tagalog: "nanay",
    kapampangan: "ima",
    luther: "indá",
    bergano: "indá, apo",
    icon: require("../assets/family/Mother.png"),
    voice_kapampangan: require("../assets/Voice/Family/MOTHER.m4a"),
  },
  {
    id: 2,
    english: "Father",
    tagalog: "tatay",
    kapampangan: "tatang",
    luther: "ibpá o táta",
    bergano: "apo, ibpá",
    icon: require("../assets/family/Father.png"),
    voice_kapampangan: require("../assets/Voice/Family/FATHER.m4a"),
  },
  {
    id: 3,
    english: "Parent",
    tagalog: "magulang",
    kapampangan: "pengari",
    luther: "táta o indú",
    bergano: "ári",
    icon: require("../assets/family/Parents.png"),
    voice_kapampangan: require("../assets/Voice/Family/PARENTS.m4a"),
  },
  {
    id: 4,
    english: "Older brother ",
    tagalog: "kuya",
    kapampangan: "koya",
    luther: "capatád á laláqu",
    bergano: "caca",
    icon: require("../assets/family/Brother.png"),
    voice_kapampangan: require("../assets/Voice/Family/OLDER_BROTHER.m4a"),
  },
  {
    id: 5,
    english: "Older Sister",
    tagalog: "ate",
    kapampangan: "atchi",
    luther: "capatád á babaí",
    bergano: "caca",
    icon: require("../assets/family/Sister.png"),
    voice_kapampangan: require("../assets/Voice/Family/OLDER_SISTER.m4a"),
  },
  {
    id: 6,
    english: "Sibling",
    tagalog: "kapatid",
    kapampangan: "capatad",
    luther: "capatád",
    bergano: "",
    icon: require("../assets/family/Siblings.png"),
    voice_kapampangan: require("../assets/Voice/Family/SIBLING.m4a"),
  },
  {
    id: 7,
    english: "Grandfather",
    tagalog: "lolo",
    kapampangan: "apu",
    luther: "ápung laláquí",
    bergano: "nunu, apo",
    icon: require("../assets/family/Grandfather.png"),
    voice_kapampangan: require("../assets/Voice/Family/Grand_Mother_Grand_Father.m4a"),
  },
  {
    id: 8,
    english: "Grandmother",
    tagalog: "lola",
    kapampangan: "apu",
    luther: "ápung babaí",
    bergn8o: "nunu, apo",
    icon: require("../assets/family/Grandmother.png"),
    voice_kapampangan: require("../assets/Voice/Family/Grand_Mother_Grand_Father.m4a"),
  },
  {
    id: 9,
    english: "Aunt",
    tagalog: "tiya",
    kapampangan: "dara",
    luther: "dára",
    bergano: "dara",
    icon: require("../assets/family/Aunt.png"),
    voice_kapampangan: require("../assets/Voice/Family/AUNT.m4a"),
  },
  {
    id: 10,
    english: "Uncle",
    tagalog: "tiyuhin",
    kapampangan: "bapa",
    luther: "bápa",
    bergano: "bapa",
    icon: require("../assets/family/Uncle.png"),
    voice_kapampangan: require("../assets/Voice/Family/UNCLE.m4a"),
  },
  {
    id: 11,
    english: "Cousin",
    tagalog: "pinsan",
    kapampangan: "pisan",
    luther: "písan",
    bergano: "catuyangan",
    icon: require("../assets/family/Cousin.png"),
    voice_kapampangan: require("../assets/Voice/Family/COUSIN.m4a"),
  },
]
